# Generated by Django 3.1.1 on 2020-10-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shippingadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
